### ISSUE TITLE
crash when pressing backspace on naming

### ISSUE THREAD

**Issue by jackytuutykcaj** [ArtixAllMighty/Telepads2016#10] opened 2017-05-16 03:47 UTC
When placing down telepad and naming.
https://pastebin.com/2tmVbjsV

**Comment by AbsolemJackdaw** [comment] 2017-05-17 12:30
thanks for the report. i'll look into fixin the 1.10.2 version when i'm done with 1.11.2 content addition !

**Comment by AbsolemJackdaw** [comment] 2017-07-17 19:30
can't seem to reproduce the error. got a crash report ?

**Comment by AbsolemJackdaw** [comment] 2017-08-02 19:41
closing this issue due to unresponsivity of interlocutor and inability on my end of reproducing the error

**Closed as completed by AbsolemJackdaw** 2017-08-02 19:41 UTC
